#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun May 08 18:54:06 IST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f8cbe18dad5c4177be36e5841b86daa7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot lightDisplay_behav xil_defaultlib.lightDisplay -log elaborate.log"
xelab -wto f8cbe18dad5c4177be36e5841b86daa7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot lightDisplay_behav xil_defaultlib.lightDisplay -log elaborate.log

